source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NewWords' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewWords
  pod 'RxCocoa', '4.1.2'
  pod 'RxSwift', '4.1.2'
  pod 'SnapKit', '4.0.0'

  target 'NewWordsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
